### ISSUE TITLE
Is there a linked query example?

### ISSUE THREAD

**Issue by jebu75** [tmcgee/cmv-widgets#12]
Is there an example using a linked query to help understand how to use these configuration options?

**Comment by tmcgee** [comment]
There isn't an example presently. The intent of the `linkedQuery` was to first execute a query to get the feature geometries and then execute a linked query to get associated attributes from a separate table. My customer that required it subsequently built a spatial view to join the geometries to the attributes. Because some code refactoring occurred after that time, I doubt any of the linkedQuery capabilities were retested. I'll see if I can come up with an example/test.

**Comment by nael14** [comment]
Hi every one, Now, Is there an example using a linked query to help understand how to use these configuration options?
