### ISSUE TITLE
Restrict Search widget to a country

### ISSUE THREAD

**Issue by srinipalavalli** [tmcgee/cmv-widgets#122]
Hi,

How can I restrict the search widget results to one country?

**Comment by tmcgee** [comment]
For the Esri Search widget you can use the `countryCode` in `localSearchOptions`. See the [documentation](https://developers.arcgis.com/javascript/3/jsapi/search-amd.html).

For my search widget, you can add any valid SQL where expression like this:
``` javascript
expression: 'country = \'US\'',
```
this expression can be added for the layer or a query within a layer.

**Comment by srinipalavalli** [comment]
Thanks Tim.

  search: {
                include: true,
                type: 'domNode',
                path: 'esri/dijit/Search',
                srcNodeRef: 'geocoderButton',
                options: {
                    map: true,
                    visible: true,
                    enableInfoWindow: true,
                    enableButtonMode: true,
                    expanded: false
				},
				sources: [{
					localSearchOptions: {
						countryCode: 'AUS'
					}
				}]
            }
is this correct?

**Comment by tmcgee** [comment]
According to the documentation, I believe you need to use a `sources` array. This is the default:
``` javascript
sources: [
  {
    locator: new   Locator("//geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer"),
    singleLineFieldName: "SingleLine",
    outFields: ["Addr_type"],
    name: i18n.widgets.Search.main.esriLocatorName,
    localSearchOptions: {
      minScale: 300000,
      distance: 50000
    },
    placeholder: i18n.widgets.Search.main.placeholder,
    highlightSymbol: new PictureMarkerSymbol(this.basePath + "/images/search-pointer.png", 36, 36).setOffset(9, 18)
  }
]
```

And not sure if you need to use the two-character country code instead of the three-character code.  The examples in the documentation use two-character codes. This repository is specific to my widgets for cmv. For general assistance with cmv, please post issues in the [cmv-app repo](https://github.com/cmv/cmv-app/issues).
