### ISSUE TITLE
Export Button in Attribute Table has no event

### ISSUE THREAD

**Issue by cuthberts** [tmcgee/cmv-widgets#133]
Hi,

I've loaded the lastest development CMV and the latest attribute and export widgets. Once I have data shown in the attribute table, I click the 'Export' button but nothing happens. It doesn't look to be sending anything on the click.

Is there a way to trouble shoot this, as the button event doesn't seem to enacting. Below is the code in the viewer.js

Any help would be amazing.
Cheers

			attributesTable: {
                include: true,
                id: 'attributesContainer',
                type: 'domNode',
                srcNodeRef: 'attributesContainer',
                path: 'gis/dijit/AttributesTable',
                options: {
                    map: true,
                    mapClickMode: true,

                    // use a tab container for multiple tables or
                    // show only a single table
                    useTabs: true,

                    // used to open the sidebar after a query has completed
                    sidebarID: 'sidebarBottom'
                }
            },
			exportDialog: {
				include: true,
    			id: 'export',
    			type: 'floating',
    			path: 'gis/dijit/Export',
    			title: 'Export',
    			options: {
					topicID: 'exportDialog',
    			    excel: true,
    			    xlsExcel: false,
     			    csv: true,

    			    shapefile: false,
    			    kml: false,
    			    kmz: false,
    			    geojson: false,
     			    topojson: false,
     			    wkt: false,

    			    defaultExportType: 'excel',

    			    // this option can be a string or a function that returns
    			    // a string.
    			    //
    			    // filename: 'my_results'
    			    /*filename: function () {
    			        var date = new Date();
    			        return 'export_results_' + date.toLocaleDateString();
    			    }*/
    			}
			}

**Comment by tmcgee** [comment]
With CMV since 2.0 beta 2 there has been a change to speed up the initial user experience. Most widgets can be loaded on demand (when opened in the sidebar, for example) instead of loading all of them when the application starts up. Export is an exception. While clicking that button could be considered "on demand", the Export widget is designed to be called from numerous places. To accomplish this, that widget needs to be loaded at startup, listening in the background, waiting to be summoned. The solution is to `preload` the Export widget. [Here](https://github.com/tmcgee/cmv-widgets/blob/master/config/search.js#L166) is the relevant property in an example configuration.

**Comment by cuthberts** [comment]
Brilliant. Thanks so much.
