### ISSUE TITLE
share function icon problem with the demo in the download

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#39]
![tim](https://cloud.githubusercontent.com/assets/6784515/10054694/689cd9be-6200-11e5-93d9-881319924852.jpg)
Also problem to implement...

**Comment by tmcgee** [comment]
@GilbertLasnier I opened your application in Chrome and looking at the Dev Tools tells me that the fonts are not found:

http://gis.icao.int/cmv-widgets-master/widgets/Share/css/fonts/tool-icons.woff
http://gis.icao.int/cmv-widgets-master/widgets/Share/fonts/tool-icons.ttf

Either those files do not exist on your server (I cannot tell) or you need to setup your IIS web server to properly serve those mime-types (file types). If it is the latter, here is a resource that should help you: http://codingstill.com/2013/01/set-mime-types-for-web-fonts-in-iis/

**Comment by GilbertLasnier** [comment]
I put the font no problem the problem now its that( i try to incorporate in my viewer but the structure of my folder is not the same then you...i have js gis digit and you you have widgets...
[cid:image001.png@01D0F610.4439C250]
[cid:image002.png@01D0F610.4439C250]

[cid:image003.png@01D0F610.4439C250]

So my folder don't have the same structure like you so I put all the element in my folder and because all the path are different nothing work
[cid:image004.png@01D0F610.4439C250]

**Comment by tmcgee** [comment]
@GilbertLasnier 

If you want to move the share widget into your dijit folder, you can do so. Just copy the `Share.js` file and the `Share` folder into your dijit folder with your other widgets. The only other change you need to make is in your `viewer.js` file. Change the `path` for the share widget to `gis/dijit/Share`.

As an aside: I use a `widgets` folder to keep my custom widgets separate from the core cmv widgets. I recommend this structure to my clients because it is easier to manage future upgrades - both for widgets and cmv.

**Comment by GilbertLasnier** [comment]
Its work your great [cid:image001.png@01D0F612.A9A436A0]  I try to copy the font on my server I just succeed to copy one font I have still the font problem but it’s much better then before because you help me…
[cid:image002.png@01D0F612.A9A436A0]
