### ISSUE TITLE
Search Widget Question

### ISSUE THREAD

**Issue by MostafaSuper** [tmcgee/cmv-widgets#5]
Question about Search Widget:

As shown below in the snapshot the current search fields render as text boxes:
![currentsearch](https://cloud.githubusercontent.com/assets/11769059/7018035/77bee798-dd08-11e4-8b02-eac6c1baba41.png)

But i need to configure some of the search fields to render as dropdown lists as shown below in the expected design:
![expectedsearch](https://cloud.githubusercontent.com/assets/11769059/7018058/8658b3e2-dd08-11e4-937c-7520c901a8ab.jpg)

So how can i configure the search fields to render as dropdown lists?

**Comment by tmcgee** [comment]
This is not possible in the current version of the Search widget though a desirable feature. Instead of using the text fields currently in the html template, I would approach this by adding the desired form fields programatically based on the UI desired (text field, date field, numeric field, drop down, etc). I may add that someday. Pull Requests to add this functionality sooner than "someday" are most welcome.

**Comment by tmcgee** [comment]
You might find the Query Builder widget found in this app helpful: http://206.169.56.48/DWH/ It is used in conjunction with my Attributes Table widget to show the results of your query. This is the main site to help understand the use case: http://www.dwhprojecttracker.org/

Please note that I did not create this Query Builder widget so I cannot provide support on how to configure it or adapt it for your needs.

**Comment by MostafaSuper** [comment]
Thanks Tim, Appreciate it i will check...

**Comment by tmcgee** [comment]
@MostafaSuper: A new [Advanced Search widget](https://github.com/vojvod/CMV_AdvancedSearch_Widget) was created by @vojvod that has some nice functionality which may be useful to you. I have not try this new widget yet.

**Comment by carrbrpoa** [comment]
I've implemented that "fixed values" stuff on @tmcgee's search widget, but didn't shared it yet (I'm noob with github collaboration) :)
