### ISSUE TITLE
Zoom To does not Zoom To ObjectID=1

### ISSUE THREAD

**Issue by pwild** [tmcgee/cmv-widgets#6]
I have included several Zoom To widgets in my app and they perform as expected except for where objectid = 1, the initial record. Nothing happens when I click the top record in the pick list. 

Just wondering if this is a bug and if so is there a fix or workaround?
Or, is there something I'm missing in the config?

I am seeing this behavior in the demo app as well.

Many thanks,
PW

**Comment by thejuskambi** [comment]
That is because of the issue in the function "search". They check for if(!this.featureIdx). since featureIdx is a number and when you check a number 0 it returns false. propably it would be good to change it to 
if(this.featureIdx === undefined) which is what needs to be checked.

**Comment by tmcgee** [comment]
@thejuskambi is correct about the cause of the issue. I have it fixed for a client installation. featureIdx is set to null so technically comparing it to `undefined` will not work when using 3 equal signs since the property is defined as a null object. 2 equal signs would work in this case but that usage is frowned upon. This is what I use:

``` javascript
if (this.featureIdx === null)
```

It will be null until a feature is selected in the drop down list then it will have a numeric value. I will submit a fix to this repo.

**Comment by tmcgee** [comment]
This has been fixed
