### ISSUE TITLE
Configurable Map Viewer-which part (variable)of the search.js grab the featurelayer url from viewer.js

### ISSUE THREAD

**Issue by cici004** [tmcgee/cmv-widgets#81]
anybody knows that which part (variable) of the search.js grab the featurelayer url (from the operational layer url in viewer.js) to only present the feauture based on search result instead of redrawing the feature layer?

**Comment by tmcgee** [comment]
@cici004 There is no variable in the Search widget that grabs the feature layer url. That widget only creates the search parameters.

The AttributesTable widget can get the url from the feature layer on the map. That is the only interaction with an existing feature layer since you can also use url that is not on the map.

All search/find operation query the REST interface to get results to present. The reason for this is that not all results are features that can be drawn on the map. Some are just records from a table.
