### ISSUE TITLE
Export not working properly with Google Chrome

### ISSUE THREAD

**Issue by JhopStl** [tmcgee/cmv-widgets#86]
I'm having an issue exporting out to an Excel or CSV table when using Google Chrome -the tool works with IE and Mozilla.  Everything works ideally up until I hit "Export to Excel Spreadsheet", then nothing happens.  

I don't think it's anything particular with my code because I was able to duplicate the issue when running the Export demo: 
http://tmcgee.github.io/cmv-widgets/demo.html?config=table

And here is my app http://map.sccmo.org

Any thoughts or ideas on what could be causing it?

Thanks,

Jesse

**Comment by JhopStl** [comment]
Edit: I was able to get this working but only when I click "Export" using both mouse buttons (right and left) simultaneously! Very strange.  I've checked on other clients machines and they have the same issue.

**Comment by tmcgee** [comment]
@JhopStl This was reported to me by a client this week as well. Something in a recent Chrome update has broken this. I have not yet identified exactly what the issue is though I suspect it has something to do with "enhanced" security when the download is started.

EDIT: One additional note: It has been reported that this issue resolves itself if you are using version 3.18 of the Esri JS API and newest version of CMV in the develop branch. More testing is required to confirm this is in fact the case.

**Comment by JhopStl** [comment]
Tim,

I figured.  I messed around with my security settings but couldn't find anything that helped fix the issue.  Another wonky workaround - press Tab (tab to the Export button) then press Enter.  I'll begin updating to the 3.18/newest CMV version, but in the meantime, I'll instruct users to use IE (ugh) and Firefox.

Thanks

**Comment by JhopStl** [comment]
I went ahead and updated the app to 3.17 and the issue resolved itself...for some reason 3.18 was giving me a tough time.

Thanks
